### ISSUE TITLE
Template is deprecated as of JUCE 6.0.8

### ISSUE THREAD

**Issue by TheWaveWarden** [TimArt/JUCE-OpenGL-Template#1]
I'm trying to compile this with JUCE 6.0.8, on Debian 11, but compilation fails:

```
Compiling OpenGLComponent.cpp
Compiling Main.cpp
Compiling BinaryData.cpp
Compiling include_juce_core.cpp
Compiling include_juce_data_structures.cpp
Compiling include_juce_events.cpp
Compiling include_juce_graphics.cpp
Compiling include_juce_gui_basics.cpp
Compiling include_juce_gui_extra.cpp
Compiling include_juce_opengl.cpp
In file included from ../../Source/OpenGLComponent.cpp:9:
../../Source/OpenGLComponent.hpp:20:7: warning: ‘OpenGLComponent’ has a field ‘OpenGLComponent::projectionMatrix’ whose type uses the anonymous namespace [-Wsubobject-linkage]
   20 | class OpenGLComponent : public Component,
      |       ^~~~~~~~~~~~~~~
../../Source/OpenGLComponent.hpp:20:7: warning: ‘OpenGLComponent’ has a field ‘OpenGLComponent::viewMatrix’ whose type uses the anonymous namespace [-Wsubobject-linkage]
../../Source/OpenGLComponent.cpp: In member function ‘virtual void OpenGLComponent::newOpenGLContextCreated()’:
../../Source/OpenGLComponent.cpp:45:30: error: ‘struct juce::OpenGLExtensionFunctions’ has no member named ‘glGenVertexArrays’
   45 |     openGLContext.extensions.glGenVertexArrays(1, &VAO); // Vertex Array Object
      |                              ^~~~~~~~~~~~~~~~~
../../Source/OpenGLComponent.cpp:50:30: error: ‘struct juce::OpenGLExtensionFunctions’ has no member named ‘glBindVertexArray’
   50 |     openGLContext.extensions.glBindVertexArray (VAO);
      |                              ^~~~~~~~~~~~~~~~~
../../Source/OpenGLComponent.cpp: In member function ‘virtual void OpenGLComponent::renderOpenGL()’:
../../Source/OpenGLComponent.cpp:100:30: error: ‘struct juce::OpenGLExtensionFunctions’ has no member named ‘glBindVertexArray’
  100 |     openGLContext.extensions.glBindVertexArray (VAO);
      |                              ^~~~~~~~~~~~~~~~~
../../Source/OpenGLComponent.cpp:102:30: error: ‘struct juce::OpenGLExtensionFunctions’ has no member named ‘glBindVertexArray’
  102 |     openGLContext.extensions.glBindVertexArray (0);
      |                              ^~~~~~~~~~~~~~~~~
make: *** [Makefile:103: build/intermediate/Debug/OpenGLComponent_fe08fa6f.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ../../Source/MainContentComponent.hpp:11,
                 from ../../Source/Main.cpp:10:
../../Source/OpenGLComponent.hpp:20:7: warning: ‘OpenGLComponent’ has a field ‘OpenGLComponent::projectionMatrix’ whose type uses the anonymous namespace [-Wsubobject-linkage]
   20 | class OpenGLComponent : public Component,
      |       ^~~~~~~~~~~~~~~
../../Source/OpenGLComponent.hpp:20:7: warning: ‘OpenGLComponent’ has a field ‘OpenGLComponent::viewMatrix’ whose type uses the anonymous namespace [-Wsubobject-linkage]

```

I am assuming something is deprecated as of this JUCE version? Or maybe I'm missing something?

**Comment by TimArt** [comment]
Ah yes, sorry about this.
This might be fixed in JUCE 6.1 where more of the OpenGL functions like these are now loaded properly:
https://juce.com/discover/stories/juce-6-1-released

But, other parts of my code will definitely break with JUCE 6.1 since I am not using the new `juce::gl::` namespace where the OpenGL functions are now living.

I'll do an upgrade soon to get this working with JUCE 6.1.
